variables:
  DOCKER_DRIVER: overlay2
  ROS_DISTRO: crystal
  base_image: ${CI_REGISTRY}/micro-ros/ci-support/micro-ros-build/microros-crystal-ros-base-dev

image: ros:${ROS_DISTRO}-ros-base

stages:
  - pkgonly
  - single
  - combined

before_script:
  - apt-get update
  - cp 20-default.list /etc/ros/rosdep/sources.list.d/
  - rosdep update
  - rosdep install -y --from-paths . -i .
  - apt install -y python3-colcon-* ed
  - git submodule init
  - git submodule update

colcon:
  stage: pkgonly
  script:
    - colcon build
  only:
    - master
    - /.*build.*/

agent_ws:
  stage: single
  script:
    - colcon build --packages-select micro_ros_setup
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_agent_ws.sh src
    - rosdep install --from-paths src -i src -y --skip-keys="rosidl_typesupport_opensplice_c rosidl_typesupport_opensplice_cpp rmw_opensplice_cpp rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp"
    - source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build
  only:
    - master
    - /.*agent.*/

firmware:
  stage: single
  script:
    - colcon build --packages-select micro_ros_setup nuttx_kconfig_vendor
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_firmware_ws.sh
    - cd firmware/NuttX
    - tools/configure.sh configs/olimex-stm32-e407/drive_base
    - cd ../..
    - ros2 run micro_ros_setup build_firmware.sh
  only:
    - master
    - /.*firmware.*/

all:
  stage: combined
  script:
    - colcon build
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_agent_ws.sh src
    - rosdep install --from-paths src -i src -y --skip-keys="rosidl_typesupport_opensplice_c rosidl_typesupport_opensplice_cpp rmw_opensplice_cpp rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp"
    - . /opt/ros/${ROS_DISTRO}/setup.bash && colcon build
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_firmware_ws.sh
    - cd firmware/NuttX
    - tools/configure.sh configs/olimex-stm32-e407/drive_base
    - cd ../..
    - ros2 run micro_ros_setup build_firmware.sh
    - test -f firmware/NuttX/nuttx

ci_base_image:
  stage: pkgonly
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t ${base_image} -f .ci-dockerfile .
    - docker push ${base_image}
  only:
    - scheduled
    - /.*ci-base-image.*/
