variables:
  DOCKER_DRIVER: overlay2
  ROS_DISTRO: crystal
  base_image: ${CI_REGISTRY}/micro-ros/ci/micro-ros-build/uros-crystal-dev
  agent_image: ${CI_REGISTRY}/micro-ros/ci/micro-ros-build/uros-crystal-agent-dev
  firmware_image: ${CI_REGISTRY}/micro-ros/ci/micro-ros-build/uros-crystal-firmware-dev
  host_client_image: ${CI_REGISTRY}/micro-ros/ci/micro-ros-build/uros-crystal-host-client-dev

image: ros:${ROS_DISTRO}-ros-base

stages:
  - docker_base
  - docker
  - pkgonly
  - single
  - combined

before_script:
  - export PATH=/usr/lib/ccache:$PATH

colcon:
  image: ${base_image}
  stage: pkgonly
  script:
    - which gcc
    - rosdep install -y --from-paths . -i .
    - colcon build --merge-install
    - ccache -s
    - test -f install/bin/kconfig && test -f install/lib/micro_ros_setup/build_firmware.sh
  only:
    - crystal
    - /.*build.*/
    - /.*ccache.*/
  except:
    variables:
      - $SCHEDULE == "docker"

agent_ws:
  image: ${agent_image}
  stage: single
  script:
    - rosdep update
    - colcon build --merge-install --packages-select micro_ros_setup
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_agent_ws.sh src
    - source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --merge-install 
    - ccache -s
    - test -f install/lib/micro_ros_agent/micro_ros_agent
  only:
    - crystal
    - /.*agent.*/
    - /.*ccache.*/
  except:
    variables:
      - $SCHEDULE == "docker"

host_client_ws:
  image: ${host_client_image}
  stage: single
  script:
    - colcon build --merge-install --packages-select micro_ros_setup
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_host_client_ws.sh
    - source /opt/ros/${ROS_DISTRO}/setup.bash && rosdep install -y --from-paths src -i src --skip-keys="microxrcedds_client microcdr rosidl_typesupport_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_opensplice_cpp rosidl_typesupport_opensplice_c rmw_connext_cpp rmw_opensplice_cpp"
    - source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --merge-install --metas src --cmake-args -DBUILD_SHARED_LIBS=ON
    - test -f install/lib/complex_msg_publisher_c/complex_msg_publisher_c
    - test -f install/lib/complex_msg_publisher_cpp/complex_msg_publisher_cpp
    - test -f install/lib/complex_msg_subscriber_c/complex_msg_subscriber_c
    - test -f install/lib/complex_msg_subscriber_cpp/complex_msg_subscriber_cpp
    - test -f install/lib/int32_publisher_c/int32_publisher_c
    - test -f install/lib/int32_publisher_cpp/int32_publisher_cpp
    - test -f install/lib/int32_subscriber_c/int32_subscriber_c
    - test -f install/lib/int32_subscriber_cpp/int32_subscriber_cpp
    - test -f install/lib/rad0_actuator_c/rad0_actuator_c
    - test -f install/lib/rad0_altitude_sensor_c/rad0_altitude_sensor_c
    - test -f install/lib/rad0_control_cpp/rad0_control_cpp
    - test -f install/lib/rad0_display_c/rad0_display_c
    - test -f install/lib/string_publisher_c/string_publisher_c
    - test -f install/lib/string_publisher_cpp/string_publisher_cpp
    - test -f install/lib/string_subscriber_c/string_subscriber_c
    - test -f install/lib/string_subscriber_cpp/string_subscriber_cpp
  only:
    - crystal 
    - /.*client.*/
    - /.*ccache.*/
  except:
    variables:
      - $SCHEDULE == "docker"

firmware:
  image: ${firmware_image}
  stage: single
  script:
    - colcon build --packages-select micro_ros_setup nuttx_kconfig_vendor
    - test -f install/bin/kconfig && test -f install/lib/micro_ros_setup/build_firmware.sh
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_firmware_ws.sh
    - cd firmware/NuttX
    - tools/configure.sh configs/olimex-stm32-e407/drive_base
    - cd ../..
    - ros2 run micro_ros_setup build_firmware.sh
    - test -f firmware/NuttX/nuttx
  only:
    - crystal
    - /.*firmware.*/
    - /.*ccache.*/
  except:
    variables:
      - $SCHEDULE == "docker"

all:
  image: ${firmware_image}
  stage: combined
  script:
    - colcon build --merge-install
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_agent_ws.sh src
    - . /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --merge-install
    - test -f install/lib/micro_ros_agent/micro_ros_agent
    - . install/local_setup.sh
    - ros2 run micro_ros_setup create_firmware_ws.sh
    - cd firmware/NuttX
    - tools/configure.sh configs/olimex-stm32-e407/drive_base
    - cd ../..
    - ros2 run micro_ros_setup build_firmware.sh
    - ccache -s
    - test -f firmware/NuttX/nuttx
  only:
    - crystal
    - /.*build-all.*/
    - /.*ccache.*/
  except:
    variables:
      - $SCHEDULE == "docker"

ci_base_image:
  stage: docker_base
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${base_image} -f micro_ros_setup/docker/Dockerfile.ci-base .
    - docker push ${base_image}
  only:
    - schedules
    - /.*ci-base-image.*/

agent_base_image:
  stage: docker
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${agent_image} --build-arg CI_REGISTRY=${CI_REGISTRY} -f micro_ros_setup/docker/Dockerfile.agent .
    - docker push ${agent_image}
  only:
    - schedules
    - /.*ci-base-image.*/

host_client_base_image:
  stage: docker
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${host_client_image} --build-arg CI_REGISTRY=${CI_REGISTRY} -f micro_ros_setup/docker/Dockerfile.host_client .
    - docker push ${host_client_image}
  only:
    - schedules
    - /.*ci-base-image.*/

firmware_base_image:
  stage: docker
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${firmware_image} --build-arg CI_REGISTRY=${CI_REGISTRY} -f micro_ros_setup/docker/Dockerfile.firmware .
    - docker push ${firmware_image}
  only:
    - schedules
    - /.*ci-base-image.*/
